# -*- coding: utf-8 -*-
"""12_python_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1spv38VP5hpNfWxCyZbrYJQTUEubvmHoK

## The 'hello world' program

1.  Open a `New notebook` in the `File` menu at the top.

2.  Name the notebook `SnapToPython.ipynb`.

3.  Enter `CTRL + ALT + T` or select `+Text` for a text block.

4.  Create a headline: `# My first Python program`.

5.  Open this Snap! file, `edit` the code and extract a picture of the
    code block: [tinyurl.com/SnapToPython](https://tinyurl.com/SnapToPython) to your PC.

6.  Create another text block and open the image symbol to `insert
       image`, then insert the PNG image that you downloaded.

7.  Now leave the editor by clicking on the crossed out pen symbol at
    the top of the text block. You should see the image embedded in
    your notebook.

8.  Create a new code block with `CTRL + ALT + I` (you can see all the
    keyboard short cuts in the sidebar at the bottom of the screen).

9.  Enter the 'hello world' program and run it with `SHIFT + ENTER`:
"""

print('hello world')

"""1.  In the next code block (that should already have appeared), enter
    another `print` statement and run it also with `SHIFT + ENTER`:


"""

print("What's your name?")

"""1.  Notice the use of single quotes in the first, and double quotes in
    the second code block: both are permitted but if you want to use
    single quotes in a *string literal* (the thing that Python should
    print), then you need to use double quotes.

2.  So far we've only seen output. To get input, like for the `ask`
    function in Snap!, we use the `input` function in Python:


"""

input()

"""1.  When you run this command, you're prompted for an input. If you
    enter nothing (or rather: the empty string `''`), you get
    nothing. If you enter something, it's played back to you.

2.  This is like the `ask` function in Snap!: the input is not stored
    anywhere. Now we store it in a variable `name` - run this command:


"""

name = input()

"""1.  And in the next code block, print the content of `name`:


"""

name

"""1.  In the next line, we use the `len` function to count the number of
    characters of the string stored in `name`:


"""

print('Your name has',len(name),'characters.')

"""1.  The result of running `len` with the argument `name` is simply
    sandwiched between two other strings.

2.  Next, we ask for the user's age. This time, we combine `print` and
    `input` by putting the `prompt` inside the parentheses, and store the
    received value in the variable `age`.


"""

age = input("What's your age? ")

"""1.  To get short information, called a *docstring* on any function, you
    can type the name followed by a question mark. For more detailed
    help, use `help(input)`:

1.  Like Snap!, Python has data types (string, number, Boolean), and
    like in Snap! you do not have to declare them but they are
    dynamically assigned when they are created by you.

2.  The next line checks the data type of `age`, which we entered as a
    number, so it's reasonable to assume that it's an integer:
"""

type(age)

"""1.  Lo and behold, it's not `int` but `str` for string! This implies that
    we cannot compute using `age` without converting it. Notice that
    Snap! did not ask us to do that.

2.  The last line contains such a computation - there are several
    things at work here:
    -   The string literal (between "") is printed as an *f-string*
        (formatted).
    -   The printed value is enclosed in {}
    -   The value is computed using `int` to convert `age` to an integer
    -   The resulting integer is added to `1`
    -   The integer is converted back to a string with `str` so that it
        can be printed:


"""

print(f"You're going to be {str(int(age)+1)} years old.")

"""1.  Here are two alternative printing ways:


"""

print("You're going to be", str(int(age)+1), "years old.")
print("You're going to be " + str(int(age)+1) + " years old.")

"""1.  To save the code blocks as one Python program `hello.py`, select
    `File` > `Download` > `Download as .py` in the top menu.

2.  Open the terminal and run the Python file on the command line:


"""