print('Hello, world!')
print("What's your name?")
name = input("What's your name? ")
print('Your name has', len(name), 'characters.')
print('Your name has ' + str(len(name)) + ' characters.')
print('a' + str(2))
print(f'Your name has {len(name)} characters.')
age = input('What is your age? ')
print('You are going to be', str(int(age) + 1), 'years old.')
print(f'You are going to be {int(age) + 1} years old.')
Age = int(age)
print(f'You are going to be {Age+1} years old')
